import assert from 'node:assert/strict';
import {analyze,checkLesson} from '../dist/src/circuit.js';
import {lessons} from '../dist/src/content.js';
import {board} from '../dist/src/boards.js';
const lesson=lessons[0],parts=lesson.components,wires=lesson.answer.wires;
const run=(w=wires,o={17:1},p=parts,pressed={})=>analyze(p,w,o,pressed);
assert.equal(board.pins.length,40);
assert.equal(board.pins[10].bcm,17);
assert.equal(new Set(board.pins.map(p=>p.physical)).size,40);
assert.equal(run().states.led1.value,1);
assert.equal(run(wires,{17:0}).states.led1.value,0);
assert.equal(run(wires,{17:.35}).states.led1.value,.35);
assert.equal(run(wires.slice(0,2)).states.led1.value,0);
assert.equal(run(wires.map(w=>({a:w.a.replace('led1:A','led1:K').replace('led1:K','led1:A'),b:w.b}))).states.led1.value,0);
const reversed=wires.map(w=>({...w,a:w.a==='led1:K'?'led1:A':w.a,b:w.b==='led1:A'?'led1:K':w.b}));
assert.equal(run(reversed).states.led1.value,0);
const noResistor=[{a:'pi:11',b:'led1:A'},{a:'led1:K',b:'pi:6'}];
assert.ok(run(noResistor).issues.some(i=>i.code.startsWith('resistor')));
assert.ok(run([...wires,{a:'pi:11',b:'led1:A'}]).issues.some(i=>i.code.startsWith('resistor')));
assert.equal(checkLesson(lesson,parts,[...wires,{a:'pi:11',b:'led1:A'}],new Set())[0].passed,false);
const alternate=wires.map(w=>({...w,b:w.b==='pi:6'?'pi:9':w.b}));
assert.equal(run(alternate).states.led1.value,1);
assert.equal(checkLesson(lesson,parts,alternate,new Set(['led1'])).every(c=>c.passed),true);
const shunt=[...wires,{a:'led1:A',b:'led1:K'}];
assert.equal(run(shunt).states.led1.value,0);
assert.ok(run([{a:'pi:1',b:'pi:2'}],{}).issues.some(i=>i.code==='source-conflict'));
assert.ok(run([{a:'pi:1',b:'pi:6'}],{}).issues.some(i=>i.code==='short'));
assert.ok(run([{a:'pi:2',b:'pi:11'}],{}).issues.some(i=>i.code==='5v-gpio'));
assert.equal(run([{a:'pi:15',b:'pi:6'}],{}).issues.length,0);
assert.equal(run([{a:'pi:15',b:'pi:11'}],{17:0}).inputs[22],1);
const button={id:'b1',type:'button',x:0,y:0};
const bw=[{a:'pi:15',b:'b1:1l'},{a:'b1:2r',b:'pi:6'}];
assert.equal(run(bw,{},[button],{}).inputs[22],0);
assert.equal(run(bw,{},[button],{b1:true}).inputs[22],1);
assert.equal(run([{a:'pi:15',b:'b1:1l'},{a:'b1:1r',b:'pi:6'}],{},[button],{}).inputs[22],1);
console.log('PASS: pin map, LED polarity/PWM/open circuits, resistor bypass, shared ground, rail conflicts, GPIO safety and button nets');
