import assert from 'node:assert/strict';
import {anchoredScroll,attachViewportGestures} from '../dist/src/viewport.js';
assert.equal(anchoredScroll(100,50,50,2),250);
assert.equal(anchoredScroll(100,50,70,1),80);
const handlers={},windowHandlers={};let zoom=1,pinchCount=0,queued=[];
globalThis.window={addEventListener:(type,fn)=>windowHandlers[type]=fn};
globalThis.requestAnimationFrame=fn=>(queued.push(fn),queued.length);
const viewport={scrollLeft:100,scrollTop:80,addEventListener:(type,fn)=>handlers[type]=fn,getBoundingClientRect:()=>({left:0,top:0}),setPointerCapture:()=>{}};
const controller=attachViewportGestures(viewport,()=>zoom,n=>zoom=n,()=>pinchCount++);
const event=(id,x,y)=>({pointerId:id,pointerType:'touch',clientX:x,clientY:y,target:{closest:()=>null},preventDefault(){},stopImmediatePropagation(){this.stopped=true;}});
handlers.pointerdown(event(1,50,50));handlers.pointerdown(event(2,150,50));
assert.ok(controller.isPinching());assert.equal(pinchCount,1);
handlers.pointermove(event(2,250,50));queued.splice(0).forEach(fn=>fn());
assert.equal(zoom,2);assert.equal(viewport.scrollLeft,250);assert.equal(viewport.scrollTop,210);
const click=event(2,250,50);handlers.click(click);assert.ok(click.stopped,'Pinch must not accidentally create a wire');
windowHandlers.pointerup(event(2,250,50));assert.equal(controller.isPinching(),false);
windowHandlers.pointercancel(event(1,50,50));assert.equal(controller.isPinching(),false);
handlers.wheel({...event(1,50,50),ctrlKey:true,deltaY:-10000});assert.equal(zoom,6);
handlers.wheel({...event(1,50,50),ctrlKey:true,deltaY:10000});assert.equal(zoom,.25);
console.log('PASS: pinch focal point, pan offset, click suppression, cancel, zoom bounds');
